/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _gamepad_t_h
#define _gamepad_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _gamepad_t gamepad_t;
struct _gamepad_t
{
    int64_t    utime;
    int8_t     present;
    int32_t    naxes;
    double     *axes;
    int64_t    buttons;
};
 
gamepad_t   *gamepad_t_copy(const gamepad_t *p);
void gamepad_t_destroy(gamepad_t *p);

typedef struct _gamepad_t_subscription_t gamepad_t_subscription_t;
typedef void(*gamepad_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const gamepad_t *msg, void *user);

int gamepad_t_publish(lcm_t *lcm, const char *channel, const gamepad_t *p);
gamepad_t_subscription_t* gamepad_t_subscribe(lcm_t *lcm, const char *channel, gamepad_t_handler_t f, void *userdata);
int gamepad_t_unsubscribe(lcm_t *lcm, gamepad_t_subscription_t* hid);
int gamepad_t_subscription_set_queue_capacity(gamepad_t_subscription_t* subs, 
                              int num_messages);


int  gamepad_t_encode(void *buf, int offset, int maxlen, const gamepad_t *p);
int  gamepad_t_decode(const void *buf, int offset, int maxlen, gamepad_t *p);
int  gamepad_t_decode_cleanup(gamepad_t *p);
int  gamepad_t_encoded_size(const gamepad_t *p);

// LCM support functions. Users should not call these
int64_t __gamepad_t_get_hash(void);
int64_t __gamepad_t_hash_recursive(const __lcm_hash_ptr *p);
int     __gamepad_t_encode_array(void *buf, int offset, int maxlen, const gamepad_t *p, int elements);
int     __gamepad_t_decode_array(const void *buf, int offset, int maxlen, gamepad_t *p, int elements);
int     __gamepad_t_decode_array_cleanup(gamepad_t *p, int elements);
int     __gamepad_t_encoded_array_size(const gamepad_t *p, int elements);
int     __gamepad_t_clone_array(const gamepad_t *p, gamepad_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
