/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "image_t.h"

static int __image_t_hash_computed;
static int64_t __image_t_hash;
 
int64_t __image_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __image_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__image_t_get_hash };
    (void) cp;
 
    int64_t hash = 0xe613eff149a08dbcLL
         + __int64_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __byte_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __image_t_get_hash(void)
{
    if (!__image_t_hash_computed) {
        __image_t_hash = __image_t_hash_recursive(NULL);
        __image_t_hash_computed = 1;
    }
 
    return __image_t_hash;
}
 
int __image_t_encode_array(void *buf, int offset, int maxlen, const image_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].stride), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].pixelformat), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].size), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, p[element].image, p[element].size);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int image_t_encode(void *buf, int offset, int maxlen, const image_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __image_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __image_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __image_t_encoded_array_size(const image_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __int64_t_encoded_array_size(&(p[element].utime), 1);
 
        size += __int16_t_encoded_array_size(&(p[element].width), 1);
 
        size += __int16_t_encoded_array_size(&(p[element].height), 1);
 
        size += __int16_t_encoded_array_size(&(p[element].stride), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].pixelformat), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].size), 1);
 
        size += __byte_encoded_array_size(p[element].image, p[element].size);
 
    }
    return size;
}
 
int image_t_encoded_size(const image_t *p)
{
    return 8 + __image_t_encoded_array_size(p, 1);
}
 
int __image_t_decode_array(const void *buf, int offset, int maxlen, image_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].stride), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].pixelformat), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].size), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].image = (uint8_t*) lcm_malloc(sizeof(uint8_t) * p[element].size);
        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, p[element].image, p[element].size);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __image_t_decode_array_cleanup(image_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_decode_array_cleanup(&(p[element].utime), 1);
 
        __int16_t_decode_array_cleanup(&(p[element].width), 1);
 
        __int16_t_decode_array_cleanup(&(p[element].height), 1);
 
        __int16_t_decode_array_cleanup(&(p[element].stride), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].pixelformat), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].size), 1);
 
        __byte_decode_array_cleanup(p[element].image, p[element].size);
        if (p[element].image) free(p[element].image);
 
    }
    return 0;
}
 
int image_t_decode(const void *buf, int offset, int maxlen, image_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __image_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __image_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int image_t_decode_cleanup(image_t *p)
{
    return __image_t_decode_array_cleanup(p, 1);
}
 
int __image_t_clone_array(const image_t *p, image_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);
 
        __int16_t_clone_array(&(p[element].width), &(q[element].width), 1);
 
        __int16_t_clone_array(&(p[element].height), &(q[element].height), 1);
 
        __int16_t_clone_array(&(p[element].stride), &(q[element].stride), 1);
 
        __int32_t_clone_array(&(p[element].pixelformat), &(q[element].pixelformat), 1);
 
        __int32_t_clone_array(&(p[element].size), &(q[element].size), 1);
 
        q[element].image = (uint8_t*) lcm_malloc(sizeof(uint8_t) * q[element].size);
        __byte_clone_array(p[element].image, q[element].image, p[element].size);
 
    }
    return 0;
}
 
image_t *image_t_copy(const image_t *p)
{
    image_t *q = (image_t*) malloc(sizeof(image_t));
    __image_t_clone_array(p, q, 1);
    return q;
}
 
void image_t_destroy(image_t *p)
{
    __image_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int image_t_publish(lcm_t *lc, const char *channel, const image_t *p)
{
      int max_data_size = image_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = image_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _image_t_subscription_t {
    image_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void image_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    image_t p;
    memset(&p, 0, sizeof(image_t));
    status = image_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding image_t!!!\n", status);
        return;
    }

    image_t_subscription_t *h = (image_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    image_t_decode_cleanup (&p);
}

image_t_subscription_t* image_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    image_t_handler_t f, void *userdata)
{
    image_t_subscription_t *n = (image_t_subscription_t*)
                       malloc(sizeof(image_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 image_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg image_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int image_t_subscription_set_queue_capacity (image_t_subscription_t* subs, 
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int image_t_unsubscribe(lcm_t *lcm, image_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe image_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

