/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _image_t_h
#define _image_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _image_t image_t;
struct _image_t
{
    int64_t    utime;
    int16_t    width;
    int16_t    height;
    int16_t    stride;
    int32_t    pixelformat;
    int32_t    size;
    uint8_t    *image;
};
 
image_t   *image_t_copy(const image_t *p);
void image_t_destroy(image_t *p);

typedef struct _image_t_subscription_t image_t_subscription_t;
typedef void(*image_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const image_t *msg, void *user);

int image_t_publish(lcm_t *lcm, const char *channel, const image_t *p);
image_t_subscription_t* image_t_subscribe(lcm_t *lcm, const char *channel, image_t_handler_t f, void *userdata);
int image_t_unsubscribe(lcm_t *lcm, image_t_subscription_t* hid);
int image_t_subscription_set_queue_capacity(image_t_subscription_t* subs, 
                              int num_messages);


int  image_t_encode(void *buf, int offset, int maxlen, const image_t *p);
int  image_t_decode(const void *buf, int offset, int maxlen, image_t *p);
int  image_t_decode_cleanup(image_t *p);
int  image_t_encoded_size(const image_t *p);

// LCM support functions. Users should not call these
int64_t __image_t_get_hash(void);
int64_t __image_t_hash_recursive(const __lcm_hash_ptr *p);
int     __image_t_encode_array(void *buf, int offset, int maxlen, const image_t *p, int elements);
int     __image_t_decode_array(const void *buf, int offset, int maxlen, image_t *p, int elements);
int     __image_t_decode_array_cleanup(image_t *p, int elements);
int     __image_t_encoded_array_size(const image_t *p, int elements);
int     __image_t_clone_array(const image_t *p, image_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
