/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "nmea_t.h"

static int __nmea_t_hash_computed;
static int64_t __nmea_t_hash;
 
int64_t __nmea_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __nmea_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__nmea_t_get_hash };
    (void) cp;
 
    int64_t hash = 0x00c245172bc5521fLL
         + __int64_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __nmea_t_get_hash(void)
{
    if (!__nmea_t_hash_computed) {
        __nmea_t_hash = __nmea_t_hash_recursive(NULL);
        __nmea_t_hash_computed = 1;
    }
 
    return __nmea_t_hash;
}
 
int __nmea_t_encode_array(void *buf, int offset, int maxlen, const nmea_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nmea), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int nmea_t_encode(void *buf, int offset, int maxlen, const nmea_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __nmea_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __nmea_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __nmea_t_encoded_array_size(const nmea_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __int64_t_encoded_array_size(&(p[element].utime), 1);
 
        size += __string_encoded_array_size(&(p[element].nmea), 1);
 
    }
    return size;
}
 
int nmea_t_encoded_size(const nmea_t *p)
{
    return 8 + __nmea_t_encoded_array_size(p, 1);
}
 
int __nmea_t_decode_array(const void *buf, int offset, int maxlen, nmea_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nmea), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __nmea_t_decode_array_cleanup(nmea_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_decode_array_cleanup(&(p[element].utime), 1);
 
        __string_decode_array_cleanup(&(p[element].nmea), 1);
 
    }
    return 0;
}
 
int nmea_t_decode(const void *buf, int offset, int maxlen, nmea_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __nmea_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __nmea_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int nmea_t_decode_cleanup(nmea_t *p)
{
    return __nmea_t_decode_array_cleanup(p, 1);
}
 
int __nmea_t_clone_array(const nmea_t *p, nmea_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);
 
        __string_clone_array(&(p[element].nmea), &(q[element].nmea), 1);
 
    }
    return 0;
}
 
nmea_t *nmea_t_copy(const nmea_t *p)
{
    nmea_t *q = (nmea_t*) malloc(sizeof(nmea_t));
    __nmea_t_clone_array(p, q, 1);
    return q;
}
 
void nmea_t_destroy(nmea_t *p)
{
    __nmea_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int nmea_t_publish(lcm_t *lc, const char *channel, const nmea_t *p)
{
      int max_data_size = nmea_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = nmea_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _nmea_t_subscription_t {
    nmea_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void nmea_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    nmea_t p;
    memset(&p, 0, sizeof(nmea_t));
    status = nmea_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding nmea_t!!!\n", status);
        return;
    }

    nmea_t_subscription_t *h = (nmea_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    nmea_t_decode_cleanup (&p);
}

nmea_t_subscription_t* nmea_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    nmea_t_handler_t f, void *userdata)
{
    nmea_t_subscription_t *n = (nmea_t_subscription_t*)
                       malloc(sizeof(nmea_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 nmea_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg nmea_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int nmea_t_subscription_set_queue_capacity (nmea_t_subscription_t* subs, 
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int nmea_t_unsubscribe(lcm_t *lcm, nmea_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe nmea_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

