/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _pose_t_h
#define _pose_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _pose_t pose_t;
struct _pose_t
{
    int64_t    utime;
    double     pos[3];
    double     vel[3];
    double     orientation[4];
    double     rotation_rate[3];
    double     accel[3];
};
 
pose_t   *pose_t_copy(const pose_t *p);
void pose_t_destroy(pose_t *p);

typedef struct _pose_t_subscription_t pose_t_subscription_t;
typedef void(*pose_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const pose_t *msg, void *user);

int pose_t_publish(lcm_t *lcm, const char *channel, const pose_t *p);
pose_t_subscription_t* pose_t_subscribe(lcm_t *lcm, const char *channel, pose_t_handler_t f, void *userdata);
int pose_t_unsubscribe(lcm_t *lcm, pose_t_subscription_t* hid);
int pose_t_subscription_set_queue_capacity(pose_t_subscription_t* subs, 
                              int num_messages);


int  pose_t_encode(void *buf, int offset, int maxlen, const pose_t *p);
int  pose_t_decode(const void *buf, int offset, int maxlen, pose_t *p);
int  pose_t_decode_cleanup(pose_t *p);
int  pose_t_encoded_size(const pose_t *p);

// LCM support functions. Users should not call these
int64_t __pose_t_get_hash(void);
int64_t __pose_t_hash_recursive(const __lcm_hash_ptr *p);
int     __pose_t_encode_array(void *buf, int offset, int maxlen, const pose_t *p, int elements);
int     __pose_t_decode_array(const void *buf, int offset, int maxlen, pose_t *p, int elements);
int     __pose_t_decode_array_cleanup(pose_t *p, int elements);
int     __pose_t_encoded_array_size(const pose_t *p, int elements);
int     __pose_t_clone_array(const pose_t *p, pose_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
