/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "raw_t.h"

static int __raw_t_hash_computed;
static int64_t __raw_t_hash;
 
int64_t __raw_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __raw_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__raw_t_get_hash };
    (void) cp;
 
    int64_t hash = 0xe42fb929da4d724cLL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __byte_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __raw_t_get_hash(void)
{
    if (!__raw_t_hash_computed) {
        __raw_t_hash = __raw_t_hash_recursive(NULL);
        __raw_t_hash_computed = 1;
    }
 
    return __raw_t_hash;
}
 
int __raw_t_encode_array(void *buf, int offset, int maxlen, const raw_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].len), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, p[element].buf, p[element].len);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int raw_t_encode(void *buf, int offset, int maxlen, const raw_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __raw_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __raw_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __raw_t_encoded_array_size(const raw_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __int64_t_encoded_array_size(&(p[element].utime), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].len), 1);
 
        size += __byte_encoded_array_size(p[element].buf, p[element].len);
 
    }
    return size;
}
 
int raw_t_encoded_size(const raw_t *p)
{
    return 8 + __raw_t_encoded_array_size(p, 1);
}
 
int __raw_t_decode_array(const void *buf, int offset, int maxlen, raw_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].len), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].buf = (uint8_t*) lcm_malloc(sizeof(uint8_t) * p[element].len);
        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, p[element].buf, p[element].len);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __raw_t_decode_array_cleanup(raw_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_decode_array_cleanup(&(p[element].utime), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].len), 1);
 
        __byte_decode_array_cleanup(p[element].buf, p[element].len);
        if (p[element].buf) free(p[element].buf);
 
    }
    return 0;
}
 
int raw_t_decode(const void *buf, int offset, int maxlen, raw_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __raw_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __raw_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int raw_t_decode_cleanup(raw_t *p)
{
    return __raw_t_decode_array_cleanup(p, 1);
}
 
int __raw_t_clone_array(const raw_t *p, raw_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);
 
        __int32_t_clone_array(&(p[element].len), &(q[element].len), 1);
 
        q[element].buf = (uint8_t*) lcm_malloc(sizeof(uint8_t) * q[element].len);
        __byte_clone_array(p[element].buf, q[element].buf, p[element].len);
 
    }
    return 0;
}
 
raw_t *raw_t_copy(const raw_t *p)
{
    raw_t *q = (raw_t*) malloc(sizeof(raw_t));
    __raw_t_clone_array(p, q, 1);
    return q;
}
 
void raw_t_destroy(raw_t *p)
{
    __raw_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int raw_t_publish(lcm_t *lc, const char *channel, const raw_t *p)
{
      int max_data_size = raw_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = raw_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _raw_t_subscription_t {
    raw_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void raw_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    raw_t p;
    memset(&p, 0, sizeof(raw_t));
    status = raw_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding raw_t!!!\n", status);
        return;
    }

    raw_t_subscription_t *h = (raw_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    raw_t_decode_cleanup (&p);
}

raw_t_subscription_t* raw_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    raw_t_handler_t f, void *userdata)
{
    raw_t_subscription_t *n = (raw_t_subscription_t*)
                       malloc(sizeof(raw_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 raw_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg raw_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int raw_t_subscription_set_queue_capacity (raw_t_subscription_t* subs, 
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int raw_t_unsubscribe(lcm_t *lcm, raw_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe raw_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

