/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _raw_t_h
#define _raw_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _raw_t raw_t;
struct _raw_t
{
    int64_t    utime;
    int32_t    len;
    uint8_t    *buf;
};
 
raw_t   *raw_t_copy(const raw_t *p);
void raw_t_destroy(raw_t *p);

typedef struct _raw_t_subscription_t raw_t_subscription_t;
typedef void(*raw_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const raw_t *msg, void *user);

int raw_t_publish(lcm_t *lcm, const char *channel, const raw_t *p);
raw_t_subscription_t* raw_t_subscribe(lcm_t *lcm, const char *channel, raw_t_handler_t f, void *userdata);
int raw_t_unsubscribe(lcm_t *lcm, raw_t_subscription_t* hid);
int raw_t_subscription_set_queue_capacity(raw_t_subscription_t* subs, 
                              int num_messages);


int  raw_t_encode(void *buf, int offset, int maxlen, const raw_t *p);
int  raw_t_decode(const void *buf, int offset, int maxlen, raw_t *p);
int  raw_t_decode_cleanup(raw_t *p);
int  raw_t_encoded_size(const raw_t *p);

// LCM support functions. Users should not call these
int64_t __raw_t_get_hash(void);
int64_t __raw_t_hash_recursive(const __lcm_hash_ptr *p);
int     __raw_t_encode_array(void *buf, int offset, int maxlen, const raw_t *p, int elements);
int     __raw_t_decode_array(const void *buf, int offset, int maxlen, raw_t *p, int elements);
int     __raw_t_decode_array_cleanup(raw_t *p, int elements);
int     __raw_t_encoded_array_size(const raw_t *p, int elements);
int     __raw_t_clone_array(const raw_t *p, raw_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
