/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "tag_detection_list_t.h"

static int __tag_detection_list_t_hash_computed;
static int64_t __tag_detection_list_t_hash;
 
int64_t __tag_detection_list_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __tag_detection_list_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__tag_detection_list_t_get_hash };
    (void) cp;
 
    int64_t hash = 0x1542f5a87a1467d7LL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __tag_detection_t_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __tag_detection_list_t_get_hash(void)
{
    if (!__tag_detection_list_t_hash_computed) {
        __tag_detection_list_t_hash = __tag_detection_list_t_hash_recursive(NULL);
        __tag_detection_list_t_hash_computed = 1;
    }
 
    return __tag_detection_list_t_hash;
}
 
int __tag_detection_list_t_encode_array(void *buf, int offset, int maxlen, const tag_detection_list_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ndetections), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __tag_detection_t_encode_array(buf, offset + pos, maxlen - pos, p[element].detections, p[element].ndetections);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int tag_detection_list_t_encode(void *buf, int offset, int maxlen, const tag_detection_list_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __tag_detection_list_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __tag_detection_list_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __tag_detection_list_t_encoded_array_size(const tag_detection_list_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __int64_t_encoded_array_size(&(p[element].utime), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].width), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].height), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].ndetections), 1);
 
        size += __tag_detection_t_encoded_array_size(p[element].detections, p[element].ndetections);
 
    }
    return size;
}
 
int tag_detection_list_t_encoded_size(const tag_detection_list_t *p)
{
    return 8 + __tag_detection_list_t_encoded_array_size(p, 1);
}
 
int __tag_detection_list_t_decode_array(const void *buf, int offset, int maxlen, tag_detection_list_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ndetections), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].detections = (tag_detection_t*) lcm_malloc(sizeof(tag_detection_t) * p[element].ndetections);
        thislen = __tag_detection_t_decode_array(buf, offset + pos, maxlen - pos, p[element].detections, p[element].ndetections);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __tag_detection_list_t_decode_array_cleanup(tag_detection_list_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_decode_array_cleanup(&(p[element].utime), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].width), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].height), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].ndetections), 1);
 
        __tag_detection_t_decode_array_cleanup(p[element].detections, p[element].ndetections);
        if (p[element].detections) free(p[element].detections);
 
    }
    return 0;
}
 
int tag_detection_list_t_decode(const void *buf, int offset, int maxlen, tag_detection_list_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __tag_detection_list_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __tag_detection_list_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int tag_detection_list_t_decode_cleanup(tag_detection_list_t *p)
{
    return __tag_detection_list_t_decode_array_cleanup(p, 1);
}
 
int __tag_detection_list_t_clone_array(const tag_detection_list_t *p, tag_detection_list_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);
 
        __int32_t_clone_array(&(p[element].width), &(q[element].width), 1);
 
        __int32_t_clone_array(&(p[element].height), &(q[element].height), 1);
 
        __int32_t_clone_array(&(p[element].ndetections), &(q[element].ndetections), 1);
 
        q[element].detections = (tag_detection_t*) lcm_malloc(sizeof(tag_detection_t) * q[element].ndetections);
        __tag_detection_t_clone_array(p[element].detections, q[element].detections, p[element].ndetections);
 
    }
    return 0;
}
 
tag_detection_list_t *tag_detection_list_t_copy(const tag_detection_list_t *p)
{
    tag_detection_list_t *q = (tag_detection_list_t*) malloc(sizeof(tag_detection_list_t));
    __tag_detection_list_t_clone_array(p, q, 1);
    return q;
}
 
void tag_detection_list_t_destroy(tag_detection_list_t *p)
{
    __tag_detection_list_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int tag_detection_list_t_publish(lcm_t *lc, const char *channel, const tag_detection_list_t *p)
{
      int max_data_size = tag_detection_list_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = tag_detection_list_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _tag_detection_list_t_subscription_t {
    tag_detection_list_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void tag_detection_list_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    tag_detection_list_t p;
    memset(&p, 0, sizeof(tag_detection_list_t));
    status = tag_detection_list_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding tag_detection_list_t!!!\n", status);
        return;
    }

    tag_detection_list_t_subscription_t *h = (tag_detection_list_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    tag_detection_list_t_decode_cleanup (&p);
}

tag_detection_list_t_subscription_t* tag_detection_list_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    tag_detection_list_t_handler_t f, void *userdata)
{
    tag_detection_list_t_subscription_t *n = (tag_detection_list_t_subscription_t*)
                       malloc(sizeof(tag_detection_list_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 tag_detection_list_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg tag_detection_list_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int tag_detection_list_t_subscription_set_queue_capacity (tag_detection_list_t_subscription_t* subs, 
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int tag_detection_list_t_unsubscribe(lcm_t *lcm, tag_detection_list_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe tag_detection_list_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

