/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _velodyne_t_h
#define _velodyne_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _velodyne_t velodyne_t;
struct _velodyne_t
{
    int64_t    utime;
    int32_t    datalen;
    uint8_t    *data;
};
 
velodyne_t   *velodyne_t_copy(const velodyne_t *p);
void velodyne_t_destroy(velodyne_t *p);

typedef struct _velodyne_t_subscription_t velodyne_t_subscription_t;
typedef void(*velodyne_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const velodyne_t *msg, void *user);

int velodyne_t_publish(lcm_t *lcm, const char *channel, const velodyne_t *p);
velodyne_t_subscription_t* velodyne_t_subscribe(lcm_t *lcm, const char *channel, velodyne_t_handler_t f, void *userdata);
int velodyne_t_unsubscribe(lcm_t *lcm, velodyne_t_subscription_t* hid);
int velodyne_t_subscription_set_queue_capacity(velodyne_t_subscription_t* subs, 
                              int num_messages);


int  velodyne_t_encode(void *buf, int offset, int maxlen, const velodyne_t *p);
int  velodyne_t_decode(const void *buf, int offset, int maxlen, velodyne_t *p);
int  velodyne_t_decode_cleanup(velodyne_t *p);
int  velodyne_t_encoded_size(const velodyne_t *p);

// LCM support functions. Users should not call these
int64_t __velodyne_t_get_hash(void);
int64_t __velodyne_t_hash_recursive(const __lcm_hash_ptr *p);
int     __velodyne_t_encode_array(void *buf, int offset, int maxlen, const velodyne_t *p, int elements);
int     __velodyne_t_decode_array(const void *buf, int offset, int maxlen, velodyne_t *p, int elements);
int     __velodyne_t_decode_array_cleanup(velodyne_t *p, int elements);
int     __velodyne_t_encoded_array_size(const velodyne_t *p, int elements);
int     __velodyne_t_clone_array(const velodyne_t *p, velodyne_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
