/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class april_jcam_ImageSourceNative */

#ifndef _Included_april_jcam_ImageSourceNative
#define _Included_april_jcam_ImageSourceNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_open_jni
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_april_jcam_ImageSourceNative_image_1source_1open_1jni
  (JNIEnv *, jclass, jstring);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_num_formats_jni
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_april_jcam_ImageSourceNative_image_1source_1num_1formats_1jni
  (JNIEnv *, jclass, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_get_format_jni
 * Signature: (II)Lapril/jcam/ImageSourceFormat;
 */
JNIEXPORT jobject JNICALL Java_april_jcam_ImageSourceNative_image_1source_1get_1format_1jni
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_set_format_jni
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_april_jcam_ImageSourceNative_image_1source_1set_1format_1jni
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_get_current_format_jni
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_april_jcam_ImageSourceNative_image_1source_1get_1current_1format_1jni
  (JNIEnv *, jclass, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_start_jni
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_april_jcam_ImageSourceNative_image_1source_1start_1jni
  (JNIEnv *, jclass, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_get_frame_jni
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_april_jcam_ImageSourceNative_image_1source_1get_1frame_1jni
  (JNIEnv *, jclass, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_stop_jni
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_april_jcam_ImageSourceNative_image_1source_1stop_1jni
  (JNIEnv *, jclass, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_close_jni
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_april_jcam_ImageSourceNative_image_1source_1close_1jni
  (JNIEnv *, jclass, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_get_num_features
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_april_jcam_ImageSourceNative_image_1source_1get_1num_1features
  (JNIEnv *, jclass, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_get_feature_name
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_april_jcam_ImageSourceNative_image_1source_1get_1feature_1name
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_get_feature_min
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_april_jcam_ImageSourceNative_image_1source_1get_1feature_1min
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_get_feature_max
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_april_jcam_ImageSourceNative_image_1source_1get_1feature_1max
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_get_feature_value
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_april_jcam_ImageSourceNative_image_1source_1get_1feature_1value
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_set_feature_value
 * Signature: (IID)I
 */
JNIEXPORT jint JNICALL Java_april_jcam_ImageSourceNative_image_1source_1set_1feature_1value
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     april_jcam_ImageSourceNative
 * Method:    image_source_enumerate_jni
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_april_jcam_ImageSourceNative_image_1source_1enumerate_1jni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
