/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package edu.umich.robot.lcmtypes;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class map_objects_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int nobjects;
    public int object_types[];
    public int object_ids[];
    public double objects[][];
 
    public map_objects_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x032121add5055b09L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(edu.umich.robot.lcmtypes.map_objects_t.class))
            return 0L;
 
        classes.add(edu.umich.robot.lcmtypes.map_objects_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.nobjects); 
 
        for (int a = 0; a < this.nobjects; a++) {
            outs.writeInt(this.object_types[a]); 
        }
 
        for (int a = 0; a < this.nobjects; a++) {
            outs.writeInt(this.object_ids[a]); 
        }
 
        for (int a = 0; a < this.nobjects; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeDouble(this.objects[a][b]); 
            }
        }
 
    }
 
    public map_objects_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public map_objects_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static edu.umich.robot.lcmtypes.map_objects_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        edu.umich.robot.lcmtypes.map_objects_t o = new edu.umich.robot.lcmtypes.map_objects_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.nobjects = ins.readInt();
 
        this.object_types = new int[(int) nobjects];
        for (int a = 0; a < this.nobjects; a++) {
            this.object_types[a] = ins.readInt();
        }
 
        this.object_ids = new int[(int) nobjects];
        for (int a = 0; a < this.nobjects; a++) {
            this.object_ids[a] = ins.readInt();
        }
 
        this.objects = new double[(int) nobjects][(int) 3];
        for (int a = 0; a < this.nobjects; a++) {
            for (int b = 0; b < 3; b++) {
                this.objects[a][b] = ins.readDouble();
            }
        }
 
    }
 
    public edu.umich.robot.lcmtypes.map_objects_t copy()
    {
        edu.umich.robot.lcmtypes.map_objects_t outobj = new edu.umich.robot.lcmtypes.map_objects_t();
        outobj.utime = this.utime;
 
        outobj.nobjects = this.nobjects;
 
        outobj.object_types = new int[(int) nobjects];
        if (this.nobjects > 0)
            System.arraycopy(this.object_types, 0, outobj.object_types, 0, this.nobjects); 
        outobj.object_ids = new int[(int) nobjects];
        if (this.nobjects > 0)
            System.arraycopy(this.object_ids, 0, outobj.object_ids, 0, this.nobjects); 
        outobj.objects = new double[(int) nobjects][(int) 3];
        for (int a = 0; a < this.nobjects; a++) {
            System.arraycopy(this.objects[a], 0, outobj.objects[a], 0, 3);        }
 
        return outobj;
    }
 
}

