#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#

Import('env')

TOHSML = env.Install('$OUT_DIR', env.Program('TOHSML', 'TOH.cpp'))
env.Alias('tohsml', TOHSML)
