/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package edu.umich.robot.lcmtypes;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class tag_detection_list_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int width;
    public int height;
    public int ndetections;
    public april.lcmtypes.tag_detection_t detections[];
 
    public tag_detection_list_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1542f5a87a1467d7L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(april.lcmtypes.tag_detection_list_t.class))
            return 0L;
 
        classes.add(april.lcmtypes.tag_detection_list_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + april.lcmtypes.tag_detection_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.width); 
 
        outs.writeInt(this.height); 
 
        outs.writeInt(this.ndetections); 
 
        for (int a = 0; a < this.ndetections; a++) {
            this.detections[a]._encodeRecursive(outs); 
        }
 
    }
 
    public tag_detection_list_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public tag_detection_list_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static april.lcmtypes.tag_detection_list_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        april.lcmtypes.tag_detection_list_t o = new april.lcmtypes.tag_detection_list_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.width = ins.readInt();
 
        this.height = ins.readInt();
 
        this.ndetections = ins.readInt();
 
        this.detections = new april.lcmtypes.tag_detection_t[(int) ndetections];
        for (int a = 0; a < this.ndetections; a++) {
            this.detections[a] = april.lcmtypes.tag_detection_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public april.lcmtypes.tag_detection_list_t copy()
    {
        april.lcmtypes.tag_detection_list_t outobj = new april.lcmtypes.tag_detection_list_t();
        outobj.utime = this.utime;
 
        outobj.width = this.width;
 
        outobj.height = this.height;
 
        outobj.ndetections = this.ndetections;
 
        outobj.detections = new april.lcmtypes.tag_detection_t[(int) ndetections];
        for (int a = 0; a < this.ndetections; a++) {
            outobj.detections[a] = this.detections[a].copy();
        }
 
        return outobj;
    }
 
}

