/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package edu.umich.robot.lcmtypes;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class waypoint_list_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int nwaypoints;
    public waypoint_t waypoints[];
 
    public waypoint_list_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8786406b95db9753L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(waypoint_list_t.class))
            return 0L;
 
        classes.add(waypoint_list_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + waypoint_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.nwaypoints); 
 
        for (int a = 0; a < this.nwaypoints; a++) {
            this.waypoints[a]._encodeRecursive(outs); 
        }
 
    }
 
    public waypoint_list_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public waypoint_list_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static waypoint_list_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        waypoint_list_t o = new waypoint_list_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.nwaypoints = ins.readInt();
 
        this.waypoints = new waypoint_t[(int) nwaypoints];
        for (int a = 0; a < this.nwaypoints; a++) {
            this.waypoints[a] = waypoint_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public waypoint_list_t copy()
    {
        waypoint_list_t outobj = new waypoint_list_t();
        outobj.utime = this.utime;
 
        outobj.nwaypoints = this.nwaypoints;
 
        outobj.waypoints = new waypoint_t[(int) nwaypoints];
        for (int a = 0; a < this.nwaypoints; a++) {
            outobj.waypoints[a] = this.waypoints[a].copy();
        }
 
        return outobj;
    }
 
}

