LDFLAGS := $(LDFLAGS) -lm -lrlutils -lrlagent -lrlgluenetdev
CFLAGS := $(CFLAGS) -Wall -pedantic

all: SampleSarsaAgent

SampleSarsaAgent: SampleSarsaAgent.o 
	$(CXX)   SampleSarsaAgent.o $(LDFLAGS) -o SampleSarsaAgent      

SampleSarsaAgent.o: SampleSarsaAgent.cpp
	$(CXX)  $(CFLAGS) -c SampleSarsaAgent.cpp -o SampleSarsaAgent.o 

clean:
	rm -rf SampleSarsaAgent SampleSarsaAgent.exe *.o









