/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package april.lcmtypes;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class raw_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int len;
    public byte buf[];
 
    public raw_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe42fb929da4d724cL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(april.lcmtypes.raw_t.class))
            return 0L;
 
        classes.add(april.lcmtypes.raw_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.len); 
 
        if (this.len > 0)
            outs.write(this.buf, 0, len);
 
    }
 
    public raw_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public raw_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static april.lcmtypes.raw_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        april.lcmtypes.raw_t o = new april.lcmtypes.raw_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.len = ins.readInt();
 
        this.buf = new byte[(int) len];
        ins.readFully(this.buf, 0, len); 
    }
 
    public april.lcmtypes.raw_t copy()
    {
        april.lcmtypes.raw_t outobj = new april.lcmtypes.raw_t();
        outobj.utime = this.utime;
 
        outobj.len = this.len;
 
        outobj.buf = new byte[(int) len];
        if (this.len > 0)
            System.arraycopy(this.buf, 0, outobj.buf, 0, this.len); 
        return outobj;
    }
 
}

